version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443
      
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: ["--version"]
